In [2]:
# Task 1.
# Import libraries
import pandas as pd
import numpy as np

# Import data

students = pd.read_csv('students.csv')
students.head()
students.notnull().sum()

gender                1000
parental_education    1000
test_prep_course      1000
math_score            1000
reading_score         1000
writing_score         1000
dtype: int64

In [3]:
# More female or male
print(students.gender.value_counts())

female    518
male      482
Name: gender, dtype: int64

In [4]:
# Average score
students.mean()

/var/folders/xh/2ng5p2655msgdgw_rhkmql1m0000gn/T/ipykernel_4931/3161043836.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  students.mean()

math_score       66.089
reading_score    69.169
writing_score    68.054
dtype: float64

In [5]:
# Perfect student
students[(students.math_score == 100) & (students.reading_score == 100) & (students.writing_score == 100)]

,gender,parental_education,test_prep_course,math_score,reading_score,writing_score
458,female,bachelor's degree,none,100,100,100
916,male,bachelor's degree,completed,100,100,100
962,female,associate's degree,none,100,100,100

In [6]:
# Average score with and without prep_course
average_prep = students[students.test_prep_course == 'completed'].math_score.mean()
print('Average score of students with test preparation course:', average_prep)

average_no_prep = students[students.test_prep_course == 'none'].math_score.mean()
print('Average score of students without test preparation course:', average_no_prep)

Average score of students with test preparation course: 69.69553072625699
Average score of students without test preparation course: 64.0778816199377

In [7]:
# Task 2.
# Load the data
salary = pd.read_csv('salary.csv')
salary.head()

   experience_years   age  salary
0               1.1   NaN   39343
1               1.3  24.0   46205
2               1.5  28.7   37731
3               NaN  31.0   43525
4               2.2   NaN   39891

In [8]:
# Filling missing values
salary.fillna({'experience_years': 3}, inplace = True)
salary.age.fillna(salary.age.mean(), inplace = True)
salary.describe()

       experience_years        age         salary
count         30.000000  30.000000      30.000000
mean           4.890000  31.216000   76003.000000
std            2.724265   3.377683   27414.429785
min            1.100000  24.000000   37731.000000
25%            3.000000  29.225000   56720.750000
50%            4.000000  31.216000   65237.000000
75%            6.600000  33.800000  100544.750000
max           10.500000  38.000000  122391.000000

In [9]:
# Checking correlation
# Correlation between salary and experience is much higher than between salary and age
# so experince seem to be more related to salary
salary.corr()

                  experience_years       age    salary
experience_years          1.000000  0.532501  0.834603
age                       0.532501  1.000000  0.519637
salary                    0.834603  0.519637  1.000000

In [10]:
# Average age of high salary employees

salary_bins = [0, 55000, 90000, 125000]

salary_names = ['Low', 'Medium', 'High']

salary['salary_cat'] = pd.cut(salary.salary, salary_bins, labels = salary_names)

print(salary.salary_cat.value_counts())

salary[salary.salary_cat == 'High'].age.mean()

Medium    13
High      11
Low        6
Name: salary_cat, dtype: int64

33.37418181818182

In [11]:
# Task 3. 
# Load data
movies = pd.read_csv('movies.csv',sep = ',',index_col = 0)
movies.head()

FileNotFoundError: [Errno 2] No such file or directory: 'movies.csv'

In [12]:
# Remove movies with less than 100 votes

movies = movies[movies.vote_count >= 100]
movies.shape

NameError: name 'movies' is not defined

In [13]:
# 3rd most frequent original language
# Japan is in the third position
movies.original_language.value_counts()[:5]

NameError: name 'movies' is not defined

In [ ]:
# Finnish movies
# Two movies, highest rated is The man without the past

movies[movies.original_language == 'fi']

In [ ]:
# Average for french and spanish movies
# Average for French movies is slightly higher

print(movies[movies.original_language == 'fr'].vote_average.mean())
print(movies[movies.original_language == 'es'].vote_average.mean())

In [ ]:
# Most frequent vote category
# Average vote between 5 and 7.5 is the most frequent

vote_bins = [-0.01, 2.5, 5, 7.5, 10]

movies['vote'] = pd.cut(movies.vote_average, vote_bins)

movies.vote.value_counts()